[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "2C5cuYgxRHohWmUsYs1unwq7joCDQR6AqD5AiE8KJkgJ"
marketplace = "9Vu2qr77epSMhaWqLgKm5uzzctAbZKJpuF3oYqaE6K5c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
